### ISSUE TITLE
Поддерживается OS Windows?

### ISSUE THREAD

**Issue by konofeev** [damage220/vim-finder#1]
Поддерживается OS Windows?
В общем то вопрос в юниксовых утилитах grep и find.

**Comment by ysoloviov** [comment]
Windows на данный момент не поддерживается. Полагаю, надо смотреть в сторону **Cygwin**.

**Comment by konofeev** [comment]
Понял.
А есть ли возможность указать пути до файлов утилит grep и find?

**Comment by ysoloviov** [comment]
В целом плагин довольно сильно кастомизируется и опции, что вас интересуют, там присутствуют. Опция `grepCommand` содержит shell команду, которая отвечает за поиск вхождений, и, по умолчанию, имеет значение `grep -ni -m %i %%s`. Для того, чтобы поиск работал, команда должна вернуть результат в виде `n:data`, где **n** - номер строки, а **data** - строка, содержащая вхождение. Я плохо знаком с окружением windows, но если там можно повторить в точности такой же шаблон, я имею ввиду разделитель в лице двоеточия, то реализовать поиск для windows будет очень просто. В противном случае придется немного переписать логику. Как вариант, я мог бы сделать поиск с помощью vim'а, но работать он будет заметно медленнее (не ощутимо, если записей менее 10.000).
